//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtRent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Customers
    {
        public int CustomerID { get; set; }
        [DisplayName("Imię Klienta")]
        public string CustomerName { get; set; }
        [DisplayName("Kraj")]
        public string Country { get; set; }
        [DisplayName("Tel. Komórkowy")]
        public Nullable<int> MobilePhone { get; set; }
    }
}
