//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yachts
    {
        public int YachtID { get; set; }
        public string YachtName { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> Cabins { get; set; }
        public Nullable<int> Beds { get; set; }
        public Nullable<int> Showers { get; set; }
        public Nullable<int> ProductionDate { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Price { get; set; }
        public string Avaliable { get; set; }
    }
}
