//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtRent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Yachts
    {
        public int YachtID { get; set; }
        [DisplayName("Nazwa jachtu")]
        public string YachtName { get; set; }
        [DisplayName("Ilość osób")]
        public Nullable<int> Capacity { get; set; }
        [DisplayName("Kabiny")]
        public Nullable<int> Cabins { get; set; }
        [DisplayName("Łóżka")]
        public Nullable<int> Beds { get; set; }
        [DisplayName("Prysznice")]
        public Nullable<int> Showers { get; set; }
        [DisplayName("Rocznik produkcji")]
        public Nullable<int> ProductionDate { get; set; }
        [DisplayName("Długość")]
        public Nullable<int> Length { get; set; }
        [DisplayName("Cena")]
        public Nullable<int> Price { get; set; }
        [DisplayName("Dostępność")]
        public string Avaliable { get; set; }
    }
}
